2025-06-02 15:36:42.436 | INFO     | __main__:<module>:41 - Logging to file: logs/project_log.log
2025-06-02 15:36:42.439 | INFO     | __main__:main:63 - STARTING utils_logger.py
2025-06-02 15:36:42.439 | INFO     | __main__:log_example:54 - This is an example info message.
2025-06-02 15:36:42.440 | WARNING  | __main__:log_example:55 - This is an example warning message.
2025-06-02 15:36:42.440 | ERROR    | __main__:log_example:56 - This is an example error message.
2025-06-02 15:36:42.440 | INFO     | __main__:main:68 - View the log output at logs/project_log.log
2025-06-02 15:36:42.441 | INFO     | __main__:main:69 - EXITING utils_logger.py.
2025-06-03 10:29:00.734 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-03 10:29:00.735 | INFO     | __main__:main:38 - Starting database setup...
2025-06-03 10:29:00.736 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/db.sqlite
2025-06-03 10:29:00.736 | ERROR    | __main__:execute_sql_file:32 - Failed to execute /Users/sydneysailors/datafun-05-sql/sql_create/01_drop_tables.sql: [Errno 2] No such file or directory: '/Users/sydneysailors/datafun-05-sql/sql_create/01_drop_tables.sql'
2025-06-03 10:29:00.737 | ERROR    | __main__:main:62 - Error during database setup: [Errno 2] No such file or directory: '/Users/sydneysailors/datafun-05-sql/sql_create/01_drop_tables.sql'
2025-06-03 10:29:00.737 | INFO     | __main__:main:65 - Database connection closed.
2025-06-03 10:35:10.504 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-03 10:35:10.505 | INFO     | __main__:main:38 - Starting database setup...
2025-06-03 10:35:10.507 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/db.sqlite
2025-06-03 10:35:10.515 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/01_drop_tables.sql
2025-06-03 10:35:10.522 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/02_create_tables.sql
2025-06-03 10:35:10.536 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/03_insert_records.sql
2025-06-03 10:35:10.536 | INFO     | __main__:main:60 - Database setup completed successfully.
2025-06-03 10:35:10.537 | INFO     | __main__:main:65 - Database connection closed.
2025-06-03 10:38:34.308 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-03 10:38:34.309 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-03 10:38:34.312 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/db.sqlite
2025-06-03 10:38:34.322 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_features/01_new_column_pub_age.sql
2025-06-03 10:38:34.322 | INFO     | __main__:main:58 - Feature queries execution completed successfully.
2025-06-03 10:38:34.324 | INFO     | __main__:main:63 - Database connection closed.
2025-06-03 10:43:23.416 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-03 10:43:23.417 | INFO     | __main__:main:38 - Starting database setup...
2025-06-03 10:43:23.424 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/db.sqlite
2025-06-03 10:43:23.447 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/01_drop_tables.sql
2025-06-03 10:43:23.462 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/02_create_tables.sql
2025-06-03 10:43:23.480 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/03_insert_records.sql
2025-06-03 10:43:23.480 | INFO     | __main__:main:60 - Database setup completed successfully.
2025-06-03 10:43:23.486 | INFO     | __main__:main:65 - Database connection closed.
2025-06-05 15:36:08.163 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-05 15:36:08.163 | INFO     | __main__:main:38 - Starting database setup...
2025-06-05 15:36:08.165 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/db.sqlite
2025-06-05 15:36:08.175 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/01_drop_tables.sql
2025-06-05 15:36:08.182 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/02_create_tables.sql
2025-06-05 15:36:08.186 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/03_insert_records.sql
2025-06-05 15:36:08.186 | INFO     | __main__:main:60 - Database setup completed successfully.
2025-06-05 15:36:08.186 | INFO     | __main__:main:65 - Database connection closed.
2025-06-05 15:48:29.656 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-05 15:48:29.657 | INFO     | __main__:main:38 - Starting database setup...
2025-06-05 15:48:29.658 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/project.sqlite3
2025-06-05 15:48:29.662 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/01_drop_tables.sql
2025-06-05 15:48:29.677 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/02_create_tables.sql
2025-06-05 15:48:29.682 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/03_insert_records.sql
2025-06-05 15:48:29.683 | INFO     | __main__:main:60 - Database setup completed successfully.
2025-06-05 15:48:29.684 | INFO     | __main__:main:65 - Database connection closed.
2025-06-05 17:00:20.200 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-05 17:00:20.200 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-05 17:00:20.203 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/project.sqlite3
2025-06-05 17:00:20.211 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_features/01_new_column_pub_age.sql
2025-06-05 17:00:20.212 | INFO     | __main__:main:58 - Feature queries execution completed successfully.
2025-06-05 17:00:20.212 | INFO     | __main__:main:63 - Database connection closed.
2025-06-05 22:19:09.414 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-05 22:19:09.414 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-05 22:19:09.417 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/project.sqlite3
2025-06-05 22:19:09.424 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/01_count_books_by_authors.sql
2025-06-05 22:19:09.427 | ERROR    | __main__:execute_sql_file:29 - Failed to execute /Users/sydneysailors/datafun-05-sql/sql_queries/query_aggregation.sql: no such column: year_published
2025-06-05 22:19:09.428 | ERROR    | __main__:main:60 - Error during feature queries execution: no such column: year_published
2025-06-05 22:19:09.428 | INFO     | __main__:main:63 - Database connection closed.
2025-06-05 22:28:13.120 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-05 22:28:13.121 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-05 22:28:13.123 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/project.sqlite3
2025-06-05 22:28:13.128 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/01_count_books_by_authors.sql
2025-06-05 22:28:13.128 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_aggregation.sql
2025-06-05 22:28:13.129 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_filter.sql
2025-06-05 22:28:13.129 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_group_by.sql
2025-06-05 22:28:13.130 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_join.sql
2025-06-05 22:28:13.130 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_sorting.sql
2025-06-05 22:28:13.130 | INFO     | __main__:main:58 - Feature queries execution completed successfully.
2025-06-05 22:28:13.130 | INFO     | __main__:main:63 - Database connection closed.
2025-06-05 22:36:08.985 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-05 22:36:08.986 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-05 22:36:08.988 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/project.sqlite3
2025-06-05 22:36:09.003 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/01_count_books_by_authors.sql
2025-06-05 22:36:09.004 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_aggregation.sql
2025-06-05 22:36:09.004 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_filter.sql
2025-06-05 22:36:09.005 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_group_by.sql
2025-06-05 22:36:09.005 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_join.sql
2025-06-05 22:36:09.005 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_sorting.sql
2025-06-05 22:36:09.005 | INFO     | __main__:main:58 - Feature queries execution completed successfully.
2025-06-05 22:36:09.005 | INFO     | __main__:main:63 - Database connection closed.
2025-06-05 22:50:35.923 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-05 22:50:35.924 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-05 22:50:35.926 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/project.sqlite3
2025-06-05 22:50:35.931 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/01_count_books_by_authors.sql
2025-06-05 22:50:35.933 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_aggregation.sql
2025-06-05 22:50:35.934 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_filter.sql
2025-06-05 22:50:35.935 | ERROR    | __main__:execute_sql_file:29 - Failed to execute /Users/sydneysailors/datafun-05-sql/sql_queries/query_group_by.sql: near "(": syntax error
2025-06-05 22:50:35.935 | ERROR    | __main__:main:60 - Error during feature queries execution: near "(": syntax error
2025-06-05 22:50:35.935 | INFO     | __main__:main:63 - Database connection closed.
2025-06-05 22:51:29.023 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-05 22:51:29.024 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-05 22:51:29.030 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/project.sqlite3
2025-06-05 22:51:29.037 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/01_count_books_by_authors.sql
2025-06-05 22:51:29.040 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_aggregation.sql
2025-06-05 22:51:29.041 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_filter.sql
2025-06-05 22:51:29.041 | ERROR    | __main__:execute_sql_file:29 - Failed to execute /Users/sydneysailors/datafun-05-sql/sql_queries/query_group_by.sql: near "(": syntax error
2025-06-05 22:51:29.042 | ERROR    | __main__:main:60 - Error during feature queries execution: near "(": syntax error
2025-06-05 22:51:29.049 | INFO     | __main__:main:63 - Database connection closed.
2025-06-05 22:54:38.643 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-05 22:54:38.644 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-05 22:54:38.647 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/project.sqlite3
2025-06-05 22:54:38.659 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/01_count_books_by_authors.sql
2025-06-05 22:54:38.660 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_aggregation.sql
2025-06-05 22:54:38.661 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_filter.sql
2025-06-05 22:54:38.662 | ERROR    | __main__:execute_sql_file:29 - Failed to execute /Users/sydneysailors/datafun-05-sql/sql_queries/query_group_by.sql: near ";": syntax error
2025-06-05 22:54:38.662 | ERROR    | __main__:main:60 - Error during feature queries execution: near ";": syntax error
2025-06-05 22:54:38.663 | INFO     | __main__:main:63 - Database connection closed.
2025-06-05 22:55:04.567 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-05 22:55:04.568 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-05 22:55:04.573 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/project.sqlite3
2025-06-05 22:55:04.580 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/01_count_books_by_authors.sql
2025-06-05 22:55:04.582 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_aggregation.sql
2025-06-05 22:55:04.583 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_filter.sql
2025-06-05 22:55:04.584 | ERROR    | __main__:execute_sql_file:29 - Failed to execute /Users/sydneysailors/datafun-05-sql/sql_queries/query_group_by.sql: no such column: authors.author_name
2025-06-05 22:55:04.584 | ERROR    | __main__:main:60 - Error during feature queries execution: no such column: authors.author_name
2025-06-05 22:55:04.585 | INFO     | __main__:main:63 - Database connection closed.
2025-06-05 22:55:29.495 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-05 22:55:29.496 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-05 22:55:29.506 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/project.sqlite3
2025-06-05 22:55:29.510 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/01_count_books_by_authors.sql
2025-06-05 22:55:29.513 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_aggregation.sql
2025-06-05 22:55:29.514 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_filter.sql
2025-06-05 22:55:29.521 | ERROR    | __main__:execute_sql_file:29 - Failed to execute /Users/sydneysailors/datafun-05-sql/sql_queries/query_group_by.sql: no such column: author
2025-06-05 22:55:29.524 | ERROR    | __main__:main:60 - Error during feature queries execution: no such column: author
2025-06-05 22:55:29.525 | INFO     | __main__:main:63 - Database connection closed.
2025-06-05 22:56:15.957 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-05 22:56:15.958 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-05 22:56:15.960 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/project.sqlite3
2025-06-05 22:56:15.967 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/01_count_books_by_authors.sql
2025-06-05 22:56:15.969 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_aggregation.sql
2025-06-05 22:56:15.970 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_filter.sql
2025-06-05 22:56:15.971 | ERROR    | __main__:execute_sql_file:29 - Failed to execute /Users/sydneysailors/datafun-05-sql/sql_queries/query_group_by.sql: ambiguous column name: author_id
2025-06-05 22:56:15.971 | ERROR    | __main__:main:60 - Error during feature queries execution: ambiguous column name: author_id
2025-06-05 22:56:15.972 | INFO     | __main__:main:63 - Database connection closed.
2025-06-05 23:02:25.063 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-05 23:02:25.064 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-05 23:02:25.070 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/project.sqlite3
2025-06-05 23:02:25.080 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/01_count_books_by_authors.sql
2025-06-05 23:02:25.082 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_aggregation.sql
2025-06-05 23:02:25.095 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_filter.sql
2025-06-05 23:02:25.098 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_group_by.sql
2025-06-05 23:02:25.099 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_join.sql
2025-06-05 23:02:25.099 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_queries/query_sorting.sql
2025-06-05 23:02:25.116 | INFO     | __main__:main:58 - Feature queries execution completed successfully.
2025-06-05 23:02:25.129 | INFO     | __main__:main:63 - Database connection closed.
