2025-06-02 15:36:42.436 | INFO     | __main__:<module>:41 - Logging to file: logs/project_log.log
2025-06-02 15:36:42.439 | INFO     | __main__:main:63 - STARTING utils_logger.py
2025-06-02 15:36:42.439 | INFO     | __main__:log_example:54 - This is an example info message.
2025-06-02 15:36:42.440 | WARNING  | __main__:log_example:55 - This is an example warning message.
2025-06-02 15:36:42.440 | ERROR    | __main__:log_example:56 - This is an example error message.
2025-06-02 15:36:42.440 | INFO     | __main__:main:68 - View the log output at logs/project_log.log
2025-06-02 15:36:42.441 | INFO     | __main__:main:69 - EXITING utils_logger.py.
2025-06-03 10:29:00.734 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-03 10:29:00.735 | INFO     | __main__:main:38 - Starting database setup...
2025-06-03 10:29:00.736 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/db.sqlite
2025-06-03 10:29:00.736 | ERROR    | __main__:execute_sql_file:32 - Failed to execute /Users/sydneysailors/datafun-05-sql/sql_create/01_drop_tables.sql: [Errno 2] No such file or directory: '/Users/sydneysailors/datafun-05-sql/sql_create/01_drop_tables.sql'
2025-06-03 10:29:00.737 | ERROR    | __main__:main:62 - Error during database setup: [Errno 2] No such file or directory: '/Users/sydneysailors/datafun-05-sql/sql_create/01_drop_tables.sql'
2025-06-03 10:29:00.737 | INFO     | __main__:main:65 - Database connection closed.
2025-06-03 10:35:10.504 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-03 10:35:10.505 | INFO     | __main__:main:38 - Starting database setup...
2025-06-03 10:35:10.507 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/db.sqlite
2025-06-03 10:35:10.515 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/01_drop_tables.sql
2025-06-03 10:35:10.522 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/02_create_tables.sql
2025-06-03 10:35:10.536 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/03_insert_records.sql
2025-06-03 10:35:10.536 | INFO     | __main__:main:60 - Database setup completed successfully.
2025-06-03 10:35:10.537 | INFO     | __main__:main:65 - Database connection closed.
2025-06-03 10:38:34.308 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-03 10:38:34.309 | INFO     | __main__:main:36 - Starting feature queries execution...
2025-06-03 10:38:34.312 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/db.sqlite
2025-06-03 10:38:34.322 | INFO     | __main__:execute_sql_file:27 - Executed: /Users/sydneysailors/datafun-05-sql/sql_features/01_new_column_pub_age.sql
2025-06-03 10:38:34.322 | INFO     | __main__:main:58 - Feature queries execution completed successfully.
2025-06-03 10:38:34.324 | INFO     | __main__:main:63 - Database connection closed.
2025-06-03 10:43:23.416 | INFO     | utils_logger:<module>:41 - Logging to file: logs/project_log.log
2025-06-03 10:43:23.417 | INFO     | __main__:main:38 - Starting database setup...
2025-06-03 10:43:23.424 | INFO     | __main__:main:52 - Connected to database: /Users/sydneysailors/datafun-05-sql/data/db.sqlite
2025-06-03 10:43:23.447 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/01_drop_tables.sql
2025-06-03 10:43:23.462 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/02_create_tables.sql
2025-06-03 10:43:23.480 | INFO     | __main__:execute_sql_file:30 - Executed: /Users/sydneysailors/datafun-05-sql/sql_create/03_insert_records.sql
2025-06-03 10:43:23.480 | INFO     | __main__:main:60 - Database setup completed successfully.
2025-06-03 10:43:23.486 | INFO     | __main__:main:65 - Database connection closed.
